### ISSUE TITLE
Add units of measurement to sensors

### ISSUE THREAD

**Issue by robbinonline** [TobiasLaross/Hass-Lynk-Co#10]
Thank you so much for this integration. Awesome to see you get so much information out of it. 
I already create a simple lovelace card and everything works. 

![IMG_4071](https://github.com/TobiasLaross/Hass-Lynk-Co/assets/660835/129fd1b2-79f0-4fcc-b58a-70a55cae932f)

I was wondering if you could add  units of measurement to the censors sensors: https://github.com/home-assistant/core/blob/d7ac4bd65379e11461c7ce0893d3533d8d8b8cbf/homeassistant/const.py#L384

Like the % for the battery, liters for the fuel etc. This gives also in ha some more customaize options for end user like set decimals. 

Can you also make a update to the service open lock that it maybe automatically updates the state. Now the lock unlocks but the state remains closed.

**Comment by TobiasLaross** [comment]
I will look into why the units of measurements doesn’t appear.

Regarding auto update I will implement something for that, but I need some throttling as well, I’m using the manual update service to update when I’m expecting an update

**Comment by TobiasLaross** [comment]
Release 1.0.1 should include the missing units

**Comment by TobiasLaross** [comment]
Release 1.1.0 includes polling when expecting state change
