### ISSUE TITLE
Home Assistant?

### ISSUE THREAD

**Issue by M1lfsh4k3** [TobiasLaross/Hass-Lynk-Co#17]
Hey i cant find any information on what Home Assistant is, on google it looks like a device. I downloaded the app and it want me to connect to a server. What do i need for this to work? Do i need purchase the device? Will it only work while the device is connected to a pc?

Thank you in advance and sorry for my lack of skills :)

**Comment by TobiasLaross** [comment]
https://www.home-assistant.io/
You need to setup a server first

**Comment by M1lfsh4k3** [comment]
Thank you, i will look into that :)

Hälsningar,
Ali Alameli
________________________________
