### ISSUE TITLE
Logs out the Android App

### ISSUE THREAD

**Issue by kuroneko007** [TobiasLaross/Hass-Lynk-Co#24]
When I add the integration in HASS, I can no longer use the Lynk & Co Android app - "Only 1 device can be used at a time". That's kind of a deal-breaker. Any workaround?

**Comment by TobiasLaross** [comment]
No that is a limitation enforced by the official app which is one of the biggest as advantages of using this integration instead (if more than 1 person wants to control the car). 
no known workarounds exists so if that is a dealbreaker than this integration is not for you unfortunately.
