### ISSUE TITLE
Only one controller

### ISSUE THREAD

**Issue by Sersant** [TobiasLaross/Hass-Lynk-Co#25]
Hi,
I managed to install the integration and it was an easy experience. I do however only get the lock/unlock controller toggle. Any Idea why?

I'm using 1.2.1.

![IMG_20240504_093528](https://github.com/TobiasLaross/Hass-Lynk-Co/assets/11733568/22a7ec9d-c912-451a-9aa5-7a106f86d945)

**Comment by TobiasLaross** [comment]
The lock controller is how home assistant handles locks in general. The other actions (climate/lights) are exposed as services
