### ISSUE TITLE
Reauthentication sets up new device with 0 entities

### ISSUE THREAD

**Issue by TobiasLaross** [TobiasLaross/Hass-Lynk-Co#43]
Reauthentication sets up new device which will have 0 entities due to duplicate IDs unless the old device is removed and hass is rebooted.

**Comment by timdows** [comment]
Today I found this same empty device
It happens when I reconfigure, i.e. enter the credentials and 2fa again

**Comment by pjgrun** [comment]
It has happened to me again. Asked for re-authentication, empty Integration Entry created, and sensors are not updated any more despite succecfully completing the re-authentication: 
![image](https://github.com/TobiasLaross/Hass-Lynk-Co/assets/89712102/9447b987-bc2c-4813-9f79-a97b39ac259a)

**Comment by TobiasLaross** [comment]
@pjgrun Yes it will happen every time you re-authenticate

**Comment by pjgrun** [comment]
Is there an easier way to recover, other than deleting the Integration Entries, re-booting and re-installing the integration again ?

**Comment by TobiasLaross** [comment]
Yes, re-authenticate, delete only the device with 120 entities and restart

**Comment by timdows** [comment]
> Yes, re-authenticate, delete only the device with 120 entities and restart

Not super formiliar with HA, but won't it than also delete the history of those entities before the restart?

**Comment by b12e** [comment]
> > Yes, re-authenticate, delete only the device with 120 entities and restart
> 
> Not super formiliar with HA, but won't it than also delete the history of those entities before the restart?

Yes it does. I lost my historical data for the months May and June doing this, so not doing it again.

**Comment by colraw** [comment]
I didn't read this issue until after I experienced it. What I did was to just delete the new one with 0 devices and restart - old one now works as before reauth with all history kept
