### ISSUE TITLE
Wow, how to start/stop charging?

### ISSUE THREAD

**Issue by lab-at-nohl** [TobiasLaross/Hass-Lynk-Co#50]
Nice work. Seeing the feature list, I miss a switch to start or stop the charging (target: get current prices into HA, automate accordingly). Is this feature planned at least?

**Comment by TobiasLaross** [comment]
Is it possible to start/stop charging in the official app? The prices can be imported to hass using other integrations (tibber/nordpool) and set up an automation with the charger

**Comment by lab-at-nohl** [comment]
I haven't found a button or alike in the app (only charging percentage). Also I am not aware of a setting inside the car, to be honest. But since I knwo it from BMW I assumed that such possibility exists - but has no ui feature yet.

**Comment by fnordpojk** [comment]
> I haven't found a button or alike in the app (only charging percentage). Also I am not aware of a setting inside the car, to be honest. But since I knwo it from BMW I assumed that such possibility exists - but has no ui feature yet.

Nope, sorry, the car has no way of controlling charging, it's all up to the charger.
