### ISSUE TITLE
Deprecated use of async_forward_entry_setup

### ISSUE THREAD

**Issue by fnordpojk** [TobiasLaross/Hass-Lynk-Co#51]
2024.9.0 tells me:

"Detected that custom integration 'lynkco' calls async_forward_entry_setup for integration, lynkco with title: Lynk & Co and entry_id: xyz, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/lynkco/__init__.py, line 354: hass.async_create_task("

Seems to be this: https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups

**Comment by kwertie01** [comment]
It seems that the error message has changed a little bit in the newer versions of HA but more importantly the date that it will stop working is moved to 2025.1 which means it stops working in one and a half month.

Detected code that calls async_forward_entry_setup for integration lynkco with title: Lynk & Co and entry_id: xxxxxxxxx, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by TobiasLaross** [comment]
Then it is about time to get it fixed, I will prioritize it
