### ISSUE TITLE
cannot config integration 

### ISSUE THREAD

**Issue by Vatiro** [TobiasLaross/Hass-Lynk-Co#52]
I'm a 2021 lynk&go 01 owner from China, I don't know whether Chinese version is different from yours or not, but I cannot config Lynk & Co Integration, it says Unknown error occurred. I'm mot sure is there any problem about my email adress, because in China, we log in lynk&go app using phone numbers, so we don't use email address to log in. If you have solutions, please let me know, thank you very much!

**Comment by TobiasLaross** [comment]
No they are different unfortunately
