### ISSUE TITLE
Engine Start/Stop not working

### ISSUE THREAD

**Issue by heuerm18** [TobiasLaross/Hass-Lynk-Co#53]
Since a few days the engine start/stop service is not working anymore. The other services like lock doors, climate, etc. are working.
Maybe Lynk&Co changed something in the function call?

**Comment by TobiasLaross** [comment]
I used it this morning and it worked

**Comment by heuerm18** [comment]
Interesting. Maybe they deactivated it for the germans. We tried the last days different times with completly charged and lower soc. We will observe it.
The other Services are working Fine. Even the pre climate with charging cable plugged in is working. Only the Engine Start/stop does nothing.

**Comment by TobiasLaross** [comment]
And you have experimental features turned on and cable not plugged in to the car?

**Comment by heuerm18** [comment]
Yes exp.features are on and cable not plugged in. I already activated debug logging. Log says that the command was successfully sent. 
maybe it is something with our car or a deactived thing on german market. I will keep an eye on it. 
But our fuel is nearly empty. Maybe that is the cause. We will refill it this evening.

**Comment by heuerm18** [comment]
We have now filled up the fuel and the engine start function is working again. So it seems that if the tank reserve warning is active the function is disabled by the car.

**Comment by TobiasLaross** [comment]
It is really good that the car actually has some limitations since this feature is not documented or supported by the official app!
Closing this issue and updating README with this info

**Comment by bjornkoster89** [comment]
Good afternoon, here (The Netherlands), the option Start/Stop will also not work. Full Full, Full Battery, and unplugged cable.
Climate controll on the cable it works good, only not start/stop without cable.
