### ISSUE TITLE
Is this a European client? 

### ISSUE THREAD

**Issue by xiaoxihu2023** [TobiasLaross/Hass-Lynk-Co#9]
Is this a European client? Chinese clients cannot use it

**Comment by TobiasLaross** [comment]
It is for European users and maybe USA, don’t know, can you confirm that it doesn’t work for Chinese?

**Comment by xiaoxihu2023** [comment]
Chinese client link: https://apps.apple.com/cn/app/lynk-co%E9%A2%86%E5%85%8B -%E4% B8% 8D% E6% AD% A2% E4% BA% 8E% E8% BD% A6/id1305517667
Chinese login accounts are all phone numbers

**Comment by TobiasLaross** [comment]
Ok, I think they have at least different login flows unfortunately.

**Comment by xiaoxihu2023** [comment]
Can you provide the European or American client link so that I can see if it can be used after synchronous registration

**Comment by TobiasLaross** [comment]
https://apps.apple.com/se/app/lynk-co/id1541599159?l=en-GB
